{{- if or .Values.mariadb.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memos.fullname" . }}-driver-auth
  labels:
    {{- include "memos.labels" . | nindent 4 }}
data:
  MEMOS_DSN: {{ include "memos.dsn" . | b64enc | quote }}
{{- end }}
