replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: dev-feed.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

# -- Configure the startup healthcheck for the containers
startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10

# -- Configure the liveness healthcheck for the containers
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10

# -- Configure the readiness healthcheck for the containers
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10

auth:
  password: r3allyPl34s3Ch4ng3M3

config: |
  logging.level.org.rm3l.devfeed=DEBUG
  datasource.poolSize=2
  executor.thread-pool.size=20

## Dependencies
mariadb:
  enabled: false

mongodb:
  enabled: false

crawlers:

  dummy:
    enabled: true

  discoverdev_io:
    enabled: false

  engineeringblogs_xyz:
    enabled: false

  rm3l_org:
    enabled: false
