apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-wg
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.wireguard.type }}
  ports:
    - port: {{ .Values.services.wireguard.port }}
      targetPort: wg
      protocol: UDP
      name: wg
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-http
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - port: {{ .Values.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
