apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-feed.fullname" . }}
  labels:
    {{- include "dev-feed.labels" . | nindent 4 }}
data:
  datasource.user: {{ default "" .Values.datasource.user | b64enc | quote }}
  datasource.password: {{ default "" .Values.datasource.password | b64enc | quote }}
  auth.password: {{ default "" .Values.auth.password | b64enc | quote }}
{{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
  datasource.mongodb.connectionString: {{ include "dev-feed.mongodbConnectionString" . | b64enc | quote }}
{{- end -}}
