
{{- if not (and (.Values.config.existingSecretRef.name) (.Values.config.existingConfigMap.name)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olivetin.fullname" . }}
  labels:
    {{- include "olivetin.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config.sample | indent 4 }}
{{- end }}